# Site settings
title: Unibg Seclab
email: seclab@unibg.it
description: > # this means to ignore newlines until "baseurl:"
  Unibg Seclab is the Computer Security Team at Università degli Studi di Bergamo.
  If you are interested in computer security, come talk to us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seclab.unibg.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Check gems allowed on github pages here: https://pages.github.com/versions/
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  tesi:
    output: true
    permalink: /tesi/:name

exclude:
  - README.md
  - vendor
