# Site settings
title: Unibg Seclab
email: seclab@unibg.it
description: > # this means to ignore newlines until "baseurl:"
  Unibg Seclab is the Computer Security Team at Università degli Studi di Bergamo.
  If you are interested in computer security, come talk to us!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://seclab.unibg.it" # the base hostname & protocol for your site

# Build settings
encoding: utf-8
markdown: kramdown
plugins: # Check allowed plugins here: https://pages.github.com/versions/
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Collections settings
collections:
  tesi:
    output: true
    permalink: /tesi/:name

# Exclude from processing
exclude:
  - README.md
  - vendor
