# Site settings
title: Unibg Seclab
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unibg-seclab.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Check gems allowed on github pages here: https://pages.github.com/versions/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

collections:
  tesi:
    output: true
    permalink: /tesi/:name
