# Site settings
title: Unibg Seclab
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unibg-seclab.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

collections:
        thesis_projects:
                output: true
                permalink: /tesi/:name
